pipeline{
    agent{
        docker{
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /root/.m2:/root/.m2.  -v /var/jenkins_home/workspace/jenkins:/usr/src/mvn '
        }
    }
    stages{
        stage('Build'){
            steps{
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
