pipeline{
    agent{
        docker{
            image 'maven:3.8.1-adoptopenjdk-11'
            args '-v /mnt/maven:/root/.m2/  -v /var/jenkins_home/workspace/jenkins:/usr/src/jenkins -w /usr/src/jenkins'
        }
    }
    stages{
        stage('Build'){
            steps{
                sh 'mvn -B -DskipTests clean package'
            }
        }
    }
}
